# The code below was originally generated by the ArcGIS Notebooks Assistant using Generative AI.
# AI-generated code may be inaccurate. Please review before using this code.

from arcgis.gis import GIS
from arcgis.features import GeoAccessor  # registered automatically when importing arcgis
import pandas as pd

# 1) Connect to your ArcGIS organization (uses the credentials of the logged-in Notebook user)
gis = GIS("home")

# 2) Path to the local feature class you want to append
#    (update this path to your actual feature class location)
fc_path = "/arcgis/home/data/mydata.gdb/my_featureclass"  # <-- change me

# 3) Read the feature class into a Spatially Enabled DataFrame (SEDF)
sdf = pd.DataFrame.spatial.from_featureclass(fc_path)
print(f"Loaded {len(sdf)} features from the source feature class")

# 4) Get the hosted feature layer you want to append to
#    Replace with the actual item ID of your hosted feature layer
hosted_fl_item_id = "YOUR_HOSTED_FEATURE_LAYER_ITEM_ID"  # <-- change me
hosted_fl = gis.content.get(hosted_fl_item_id).layers[0]

# 5) Append the new features
#    Option A – using the append operation (preferred for large datasets)
append_result = hosted_fl.append(
    inputs=sdf,             # the SEDF containing the features to add
    upload_format="pandas", # tells the service we are sending a pandas DataFrame
    upsert=False,           # create new features; do not try to match and update
    skip_updates=False,
    skip_inserts=False
)
print("Append (async) job status:", append_result)

# ----
# Option B – if you prefer an immediate, synchronous add (usually fine for small inputs):
# fs = sdf.spatial.to_featureset()
# edit_result = hosted_fl.edit_features(adds=fs)
# print("Edit features result:", edit_result)
